package io.sentinel.shared.model;
public enum MentionCategory {
  PAYMENT_FAILURE, APP_CRASH, SLOW_PERFORMANCE, WRONG_CHARGE, KYC_ISSUE,
  ACCOUNT_BLOCKED, FRAUD_REPORT, GENERAL_COMPLAINT, FEATURE_REQUEST,
  COMPLIMENT, QUERY, REGULATORY, OTHER
}