package io.squados.examples.tutoros.model;

import io.squados.annotation.OutputField;

/**
 * An animated or static visual asset generated by VisualisationAgent.
 *
 * SquadOS: @StructuredOutput(schema = VisualAsset.class)
 *
 * The VisualisationAgent selects the render type based on the concept:
 *   SVG    — inline diagrams, flow charts, structure labels (instant, no server needed)
 *   D3JS   — interactive graphs, data plots, real-time animations (runs in browser)
 *   MANIM  — cinematic step-by-step mathematical/scientific animations (Python, server-side)
 *
 * The rendered payload is embedded directly in the chat as an HTML block
 * or as a video src for Manim outputs.
 */
public class VisualAsset {

    @OutputField(description = "Render type: SVG | D3JS | MANIM", example = "D3JS")
    public String renderType;

    @OutputField(description = "Concept this visual explains", example = "electron transport chain")
    public String concept;

    @OutputField(description = "Title for the visual", example = "Z-Scheme: Electron Flow in Light Reactions")
    public String title;

    @OutputField(description = "For SVG: the full <svg>...</svg> markup to embed inline")
    public String svgMarkup;

    @OutputField(description = "For D3JS: self-contained JavaScript that renders into a <div id='viz'>")
    public String d3Script;

    @OutputField(description = "For MANIM: the Python Manim scene script to be executed server-side")
    public String manimScript;

    @OutputField(description = "For MANIM: URL of the rendered MP4 once the render job completes")
    public String videoUrl;

    @OutputField(description = "Alt-text description of the visual for accessibility")
    public String altText;

    @OutputField(description = "Whether the visual is interactive (user can hover/click)", example = "true")
    public boolean interactive;
}
