package io.squados.dashboard.api.controller;

import io.squados.dashboard.api.model.ApprovalItem;
import io.squados.dashboard.api.service.DashboardDataService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Read-only view of approval requests generated by @AwaitApproval agents.
 * The dashboard is a monitoring tool — it does not approve or reject requests.
 *
 * GET /api/v1/approvals            — all approvals (filter by ?status=PENDING|APPROVED|REJECTED)
 * GET /api/v1/approvals/{id}       — single approval detail
 */
@RestController
@RequestMapping("/api/v1/approvals")
public class ApprovalController {

    private final DashboardDataService dataService;

    public ApprovalController(DashboardDataService dataService) {
        this.dataService = dataService;
    }

    @GetMapping
    public ResponseEntity<List<ApprovalItem>> listApprovals(
            @RequestParam(name = "status", required = false) String status) {
        return ResponseEntity.ok(dataService.getApprovals(status));
    }

    @GetMapping("/{id}")
    public ResponseEntity<ApprovalItem> getApproval(@PathVariable("id") String id) {
        return dataService.getApprovals(null).stream()
                .filter(a -> a.id().equals(id))
                .findFirst()
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }
}
