import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { generateFlashcards, type GenerateParams } from '@/lib/generate';
import type { Flashcard } from '@/lib/types';

/** Reviewer rating for SM-2-style scheduling. */
export type Grade = 'again' | 'hard' | 'good' | 'easy';

interface PracticeState {
  cards: Flashcard[];
  cursor: number;
  flipped: boolean;
  isGenerating: boolean;
  lastError: string | null;

  flip: () => void;
  next: () => void;
  grade: (g: Grade) => void;
  /** Replace/append cards generated by the tutor backend. */
  addCards: (cards: Flashcard[]) => void;
  /** Remove every card tied to a topic (so re-generate is idempotent). */
  clearAll: () => void;
  /** Ask the backend (or mock) to produce a fresh batch of cards. */
  generate: (params: GenerateParams) => Promise<Flashcard[]>;

  /** All cards whose `due` timestamp is now-or-earlier */
  dueQueue: () => Flashcard[];
}

export const usePractice = create<PracticeState>()(
  persist(
    (set, get) => ({
      cards: [],
      cursor: 0,
      flipped: false,
      isGenerating: false,
      lastError: null,

      flip: () => set(s => ({ flipped: !s.flipped })),
      next: () => set(s => ({
        cursor: Math.min(s.cursor + 1, get().dueQueue().length),
        flipped: false,
      })),
      grade: (g) => {
        const queue = get().dueQueue();
        const card = queue[get().cursor];
        if (!card) return;
        set(s => ({
          cards: s.cards.map(c => c.id === card.id ? scheduleSM2(c, g) : c),
        }));
        get().next();
      },
      addCards: (cards) => set(s => {
        const seen = new Set(s.cards.map(c => c.id));
        const fresh = cards.filter(c => !seen.has(c.id));
        return { cards: [...s.cards, ...fresh], cursor: 0, flipped: false };
      }),
      clearAll: () => set({ cards: [], cursor: 0, flipped: false }),

      generate: async (params) => {
        set({ isGenerating: true, lastError: null });
        try {
          const cards = await generateFlashcards(params);
          get().addCards(cards);
          set({ isGenerating: false });
          return cards;
        } catch (e) {
          set({
            isGenerating: false,
            lastError: e instanceof Error ? e.message : String(e),
          });
          throw e;
        }
      },

      dueQueue: () => {
        const now = Date.now();
        return get().cards
          .filter(c => new Date(c.due).getTime() <= now)
          .sort((a, b) => new Date(a.due).getTime() - new Date(b.due).getTime());
      },
    }),
    {
      name: 'tutoros.practice',
      storage: createJSONStorage(() => localStorage),
      version: 1,
      partialize: (s) => ({ cards: s.cards }),
    }
  )
);

/** Light SM-2 implementation — keeps the example honest about what SRS does. */
function scheduleSM2(c: Flashcard, g: Grade): Flashcard {
  const ease = Math.max(1.3,
    g === 'again' ? c.ease - 0.2 :
    g === 'hard'  ? c.ease - 0.15:
    g === 'good'  ? c.ease       :
                    c.ease + 0.1
  );
  const interval =
    g === 'again' ? 1 :
    g === 'hard'  ? Math.max(1, Math.round(c.intervalDays * 1.2)) :
    g === 'good'  ? Math.round(c.intervalDays * ease) :
                    Math.round(c.intervalDays * ease * 1.3);
  const due = new Date(Date.now() + interval * 86400e3).toISOString();
  return { ...c, ease, intervalDays: interval, due };
}
