spring.main.web-application-type=none
server.port=8080
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.5
spring.ai.ollama.chat.options.stream=false
redis.host=localhost
redis.port=6379
